### ISSUE TITLE
No connection, but no intersection

### ISSUE THREAD

**Issue by bhny** [meshcenter/line-of-sight#9]
Sometimes it shows no intersection but also says no connection-
<img width="604" alt="Screen Shot 2019-07-21 at 2 57 57 PM" src="https://user-images.githubusercontent.com/1037006/61595675-212e4480-abc8-11e9-83fd-05ad5e678696.png">

There actually is LoS to SN1 in this case

https://los.nycmesh.net/search?address=32%20Spring%20Street%2C%20Manhattan%2C%20New%20York%2010012&bin=1007181

**Comment by nuyawktuah** [comment]
Fixed in https://github.com/nycmeshnet/line-of-sight/commit/050ef4f6a1ad73b791958f147fc5ea23163953df
